### PR TITLE
Connect-to-Api

### PR DESCRIPTION
**Pull request by Patfarmurs**

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @Patfarmurs 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

# Interesting job, I only wish I could have approved this :disappointed: 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7




## Highlights
 - [x]  Correct GitFlow  ✅
 - [x]  Good commit history  ✅
 - [x]  Good PR title/description  ✅
 - [x]  All linters passed  ✅
 
## Required Changes ♻️
 - [x] Good job adding the MIT file, The problem is you need to update its content in regard to your name and project title. Please replace the `[YOUR NAME]` part with your name, `[APP TYPE]` with your app type, and the [YEAR] with the current year. 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Patfarmurs** [comment]
Thank you @TadesseDev, issues are resolved.

**Review by Shedrack-Sunday — APPROVED** [review]
Hi @Patfarmurs 

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

image


## Highlights
- Descriptive PR ✔️
- Nice README structure✔️
- Correct GitHub flow ✔️

## Confirmed changes by last review request
image


## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Patfarmurs** [comment]
Thank you @Shedrack-Sunday

**Pull request merged**
